### PR TITLE
Change of POST createEvent request with axios

### PR DESCRIPTION
**Pull request by DusanSacha**
Hi @gregorwolf ,
I use axios in one file for now. Test looks good!
I created this my first pull request - just to see how the process (code, save, pull) works.

### CODE REVIEW

**Comment by gregorwolf** [comment]
Please also commit the adjustment to package.json as axios currently isn't part of the dependencies.

**Comment by DusanSacha** [comment]
I can do it. 
However when I checked, axios is required by package "/@sap/cloud-sdk-core" and therefore should be already there "by default".  Thats why I thought it is fine like this. What do you think?

**Comment by gregorwolf** [comment]
I think we currently have no direct use for @sap/cloud-sdk-core so we might be better off to define axios directly. But maybe it would even be better to use the SAP Cloud SDK, building a custom client and have full typed support for the requests in the tests. What do you think?

**Comment by DusanSacha** [comment]
I have not explored SAP Cloud SDK yet, so I cannot give any reasonable thoughts to this topic :) 
Going to check some materials about the SDK.

**Pull request merged**
