### PR TITLE
Organizer service

### PR DESCRIPTION
**Pull request by balbinosoares**
**Changes in data-model:** 
Included enum to Active (Yes/No). Adjusted the name for keep pattern with other entities.
**Changes in admin-service**
Created entity ParticipantsPerEventRead, adjustment in associations, and Capabilities

**Create admin-service.js, organizer-service.js, organizer-service.cds**

### CODE REVIEW

**Comment by gregorwolf** [comment]
Do we have to include all the XML files? I would think they are build results and we can exclude them or?

**Comment by NabheetCloud** [comment]
can you please also rename organizer-admin.js to oraganizer-service.

**Comment by balbinosoares** [comment]
Sorry..., Yes the XML files are build results and you can exclude then.  can you merge only the other files or I need to remove before?

**Comment by balbinosoares** [comment]
> can you please also rename organizer-admin.js to oraganizer-service.

Sorry... 

I did it now

**Comment by gregorwolf** [comment]
I would think you can use git rm <filename>, commit the changes to your branch and update the pull request.

**Comment by gregorwolf** [comment]
Thank you for removing the XML files. Can you please check the .js files with your CREATE and READ hooks? The console.log doesn't always represents what's done there. Also there is a comment left over from the bookstore.

**Pull request merged**
